export enum errorMessage {
  INTERNAL_SERVER_ERROR = 'Erro interno no servidor.',
  UNREGISTERED_USER = 'Usuário não cadastrado.',
  WRONG_PASSWORD = 'Senha invalida.',
  ALREADY_REGISTERED_EMAIL = 'E-mail já foi registrado.',
  ALREADY_SIGNED_IN = 'Esta sessão já esta iniciada.',
  INVALID_FIRSTNAME = 'Nome invalido.',
  INVALID_LASTNAME = 'Sobrenome invalido.',
  INVALID_AGE = 'Idade invalida.',
  INVALID_EMAIL = 'E-mail invalido.',
  INVALID_PASSWORD = 'Senha invalida. ',
  INVALID_TOKEN = 'Token invalido.',
  INVALID_SESSION_TOKEN = 'Esta sessão não esta iniciada.',
  CANNOT_CREATE_SESSION_TOKEN = 'Não foi possivel iniciar sessão.',
}
